export * from './Chil'
export * from './Home'
export * from './Course'
export * from './CourseDetail'
export * from './contact'
export * from './Recruit'
export * from './RecruitDetail'
export * from './ForMe'
